
Vagrant.configure(2) do |ruby_dev|

  ruby_dev.vm.box = "ubuntu/trusty64"
  ruby_dev.vm.network "public_network"
  ruby_dev.vm.network "forwarded_port", guest: "3000", host: "3031"
  ruby_dev.vm.provision "shell", path: "tasks.sh"

end
