Vagrant.configure(2) do |config|

  config.vm.box = "centos/7"
  config.vm.network "forwarded_port", guest: 80, host: 8480
  config.vm.network "public_network"
  config.vm.provision "shell", path: "zabbix-server-installer.sh"

end